name: Deploy

on:
    push:
        branches: [ master ]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                cache: 'npm'
            - name: Test
              run: |
                npm ci
                npm run test
    deploy:
        runs-on: ubuntu-latest
        needs: test
        environment: garypippi.net
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                cache: 'npm'
            - name: Deploy
              env:
                  SSH_KEY: ${{ secrets.SSH_KEY }}
                  SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
                  SSH_USER: ${{ secrets.SSH_USER }}
                  SSH_HOST: ${{ secrets.SSH_HOST }}
                  S3_PATH: ${{ secrets.S3_PATH }}
                  SNS_TWITTER_URL: ${{ secrets.SNS_TWITTER_URL }}
                  SNS_GITHUB_URL: ${{ secrets.SNS_GITHUB_URL }}
                  GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
              run: |
                  echo "S3_PATH=$S3_PATH" >> .env.local
                  echo "SNS_TWITTER_URL=$SNS_TWITTER_URL" >> .env.local
                  echo "SNS_GITHUB_URL=$SNS_GITHUB_URL" >> .env.local
                  echo "GOOGLE_ANALYTICS_ID=$GOOGLE_ANALYTICS_ID" >> .env.local
                  git submodule init
                  git submodule update
                  npm ci
                  npm run build
                  npm run export
                  mkdir -m 700 ~/.ssh
                  echo "$SSH_KEY" > ~/.ssh/id_rsa
                  echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
                  chmod 600 ~/.ssh/id_rsa
                  rsync -a --delete out/ $SSH_USER@$SSH_HOST:garypippi.net/
