name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - name: Test
        run: |
          npm ci
          npm run test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: garypippi.net
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - name: Deploy
        run: |
          echo "NEXT_PUBLIC_SITE_TITLE=${{ vars.NEXT_PUBLIC_SITE_TITLE }}" >> .env.local
          echo "NEXT_PUBLIC_VIDEO_PATH=${{ vars.NEXT_PUBLIC_VIDEO_PATH }}" >> .env.local
          echo "NEXT_PUBLIC_IMAGE_PATH=${{ vars.NEXT_PUBLIC_IMAGE_PATH }}" >> .env.local
          echo "NEXT_PUBLIC_NAME=${{ vars.NEXT_PUBLIC_NAME }}" >> .env.local
          echo "NEXT_PUBLIC_TWITTER=${{ vars.NEXT_PUBLIC_TWITTER }}" >> .env.local
          echo "NEXT_PUBLIC_GITHUB=${{ vars.NEXT_PUBLIC_GITHUB }}" >> .env.local
          echo "BLOG_PATH=blog" >> .env.local
          git clone "${{ vars.BLOG_CLONE_URL }}" blog
          npm ci
          npm run build
          npm run export
          npm run build:cli
          HOST_URL="${{ vars.HOST_URL }}" node ./cli/index.mjs sitemap
          mkdir -m 700 ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          rsync -a --delete -e "ssh -p ${{ secrets.SSH_PORT }}" out/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_PATH }}/
